module.exports = [
  // ════════════════════════════════════════════════════════════════
  // LITERASI - MEMBACA
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH (Pengenalan Huruf) ──
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'pilihan_ganda', difficulty: 1, question: 'Huruf apakah ini: "A"?', answer: 'Huruf A', options: ['Huruf A', 'Huruf B', 'Huruf C', 'Huruf D'], explanation: 'Huruf A adalah huruf pertama dalam abjad Indonesia.' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'pilihan_ganda', difficulty: 1, question: 'Huruf kapital dari "b" adalah...', answer: 'B', options: ['A', 'B', 'D', 'P'], explanation: 'Huruf kecil "b" jika ditulis besar menjadi "B".' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'isian', difficulty: 1, question: 'Isi huruf yang hilang: _BCDEFG', answer: 'A', explanation: 'Huruf pertama abjad adalah A, sehingga urutannya ABCDEFG.' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'isian', difficulty: 1, question: 'Huruf kecil dari "M" adalah...', answer: 'm', explanation: 'Huruf kapital "M" jika ditulis kecil menjadi "m".' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'pilihan_ganda', difficulty: 1, question: 'Huruf "R" terletak setelah huruf...', answer: 'Q', options: ['O', 'P', 'Q', 'S'], explanation: 'Urutan abjad: ...O, P, Q, R, S...' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'pilihan_ganda', difficulty: 1, question: 'Berapa jumlah huruf vokal?', answer: '5 huruf', options: ['3 huruf', '4 huruf', '5 huruf', '6 huruf'], explanation: 'Huruf vokal: A, I, U, E, O = 5 huruf.' },
  { category: 'membaca', subcategory: 'pengenalan_huruf', type: 'isian', difficulty: 1, question: 'Tuliskan huruf vokal ke-3:', answer: 'U', explanation: 'Huruf vokal: A(1), I(2), U(3), E(4), O(5).' },

  // ── LEVEL 2: MUDAH (Menyusun Kata & Pengertian Kata) ──
  { category: 'membaca', subcategory: 'menyusun_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Susun huruf "KUCING" dengan benar:', answer: 'KUCING', options: ['KUCING', 'CUKING', 'KUCNIG', 'KINGUC'], explanation: 'Kata yang benar adalah KUCING (hewan berbulu).'},
  { category: 'membaca', subcategory: 'menyusun_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Kata "RUMAH" terdiri dari berapa suku kata?', answer: '2 suku kata', options: ['1 suku kata', '2 suku kata', '3 suku kata', '4 suku kata'], explanation: 'RU-MAH = 2 suku kata.' },
  { category: 'membaca', subcategory: 'menyusun_kata', type: 'isian', difficulty: 2, question: 'Susun kata: GULA = ?', answer: 'GULA', explanation: 'GULA adalah bahan manis untuk minuman.' },
  { category: 'membaca', subcategory: 'pengertian_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Apa arti kata "CERAH"?', answer: 'Terang', options: ['Gelap', 'Terang', 'Basah', 'Dingin'], explanation: 'Cerah berarti terang, tidak mendung, matahari bersinar.' },
  { category: 'membaca', subcategory: 'pengertian_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Makna kata "RAJIN" adalah...', answer: 'Suka bekerja keras', options: ['Suka bermain', 'Suka bekerja keras', 'Suka malas', 'Suka tidur'], explanation: 'Rajin berarti giat, tidak malas-malasan dalam bekerja.' },
  { category: 'membaca', subcategory: 'pengertian_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Kata "BESAR" adalah kebalikan dari kata...', answer: 'Kecil', options: ['Tinggi', 'Panjang', 'Kecil', 'Lebar'], explanation: 'Besar dan kecil adalah pasangan kata berlawanan.' },
  { category: 'membaca', subcategory: 'pengertian_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Apa arti kata "TERBANG"?', answer: 'Berada di udara', options: ['Berjalan', 'Berada di udara', 'Berlari', 'Berenang'], explanation: 'Terbang artinya bergerak atau berada di udara.' },

  // ── LEVEL 3: SEDANG (Membaca Kalimat & Memahami Teks) ──
  { category: 'membaca', subcategory: 'membaca_kalimat', type: 'pilihan_ganda', difficulty: 3, question: 'Manakah kalimat yang benar?', answer: 'Ibu sedang memasak di dapur.', options: ['Ibu sedang memasak di dapur.', 'Ibu sedang masak di dapurnya.', 'Ibunya sedang memasak dapur.', 'Di dapur ibu sedang memasak.'], explanation: 'Kalimat yang benar dan lengkap: Subjek + Predikat + Objek + Keterangan.' },
  { category: 'membaca', subcategory: 'membaca_kalimat', type: 'isian', difficulty: 3, question: 'Lengkapi: Anak-anak ___ di taman.', answer: 'bermain', options: ['bermain', 'tidur', 'makan', 'minum'], explanation: 'Kalimat yang tepat: Anak-anak bermain di taman.' },
  { category: 'membaca', subcategory: 'memahami_teks', type: 'pilihan_ganda', difficulty: 3, question: '"Andi pergi ke sekolah setiap hari." Kapan Andi pergi ke sekolah?', answer: 'Setiap hari', options: ['Hari Senin', 'Setiap hari', 'Hari Minggu', 'Setiap bulan'], explanation: 'Teks menyatakan "setiap hari" artinya selalu, setiap hari.' },
  { category: 'membaca', subcategory: 'memahami_teks', type: 'pilihan_ganda', difficulty: 3, question: 'Bacaan: "Budi suka membaca buku." Apa hobi Budi?', answer: 'Membaca buku', options: ['Bermain bola', 'Membaca buku', 'Menonton TV', 'Bersepeda'], explanation: 'Teks menyebutkan Budi suka membaca buku.' },
  { category: 'membaca', subcategory: 'membaca_kalimat', type: 'pilihan_ganda', difficulty: 3, question: 'Kalimat berikut yang benar adalah...', answer: 'Kucing itu berlari cepat.', options: ['Kucing itu berlari cepat.', 'Kucing berlari itu cepat.', 'Cepat kucing itu berlari.', 'Berlari kucing cepat itu.'], explanation: 'Urutan yang benar: subjek + kata penghubung + predikat + keterangan.' },
  { category: 'membaca', subcategory: 'memahami_teks', type: 'pilihan_ganda', difficulty: 3, question: '"Saya minum air putih setelah olahraga." Mengapa minum air putih?', answer: 'Karena haus setelah olahraga', options: ['Karena lapar', 'Karena haus setelah olahraga', 'Karena ingin berenang', 'Karena dingin'], explanation: 'Setelah olahraga tubuh kehilangan cairan sehingga haus.' },

  // ── LEVEL 4: SULIT (Paragraf & Inferensi) + HOT ──
  { category: 'membaca', subcategory: 'membaca_paragraf', type: 'pilihan_ganda', difficulty: 4, question: '"Rina bangun pagi. Ia sarapan lalu berangkat sekolah." Apa yang dilakukan Rina setelah sarapan?', answer: 'Berangkat sekolah', options: ['Tidur lagi', 'Berangkat sekolah', 'Main games', 'Membersihkan rumah'], explanation: 'Berdasarkan urutan cerita: bangun → sarapan → berangkat sekolah.' },
  { category: 'membaca', subcategory: 'membaca_paragraf', type: 'pilihan_ganda', difficulty: 4, question: 'Paragraf di atas menceritakan tentang...', answer: 'Aktivitas Rina', options: ['Aktivitas Rina', 'Hewan peliharaan', 'Cuaca hari ini', 'Makanan favorit'], explanation: 'Paragraf menceritakan aktivitas Rina dari bangun pagi hingga berangkat sekolah.' },
  { category: 'membaca', subcategory: 'inferensi_teks', type: 'pilihan_ganda', difficulty: 4, question: '"Sinta membawa payung karena langit mendung." Mengapa Sinta membawa payung?', answer: 'Karena akan hujan', options: ['Karena panas', 'Karena akan hujan', 'Karena mau berenang', 'Karena mau bermain'], explanation: 'Langit mendung adalah tanda akan turun hujan.' },
  { category: 'membaca', subcategory: 'inferensi_teks', type: 'pilihan_ganda', difficulty: 4, question: '"Riko minum air setelah berolahraga." Mengapa Riko minum air?', answer: 'Karena haus', options: ['Karena lapar', 'Karena haus', 'Karena dingin', 'Karena mau mandi'], explanation: 'Setelah berolahraga tubuh membutuhkan cairan sehingga haus.' },

  // ── LEVEL 4 HOT: Analisis & Evaluasi ──
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 4, question: 'Bacaan: "Andaikan saya adalah presiden, saya akan membangun sekolah di setiap desa." Kalimat tersebut merupakan...', answer: 'Harapan atau keinginan', options: ['Fakta yang terjadi', 'Harapan atau keinginan', 'Perintah', 'Pertanyaan'], explanation: 'Kata "andaikan" menunjukkan kalimat ini adalah harapan/keinginan, bukan fakta.' },
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 4, question: '"Makanan sehat membuat tubuh kuat, sedangkan makanan tidak sehat membuat tubuh lemah." Hubungan kedua kalimat tersebut adalah...', answer: 'Perbandingan berlawanan', options: ['Sebab-akibat', 'Perbandingan berlawanan', 'Urutan waktu', 'Contoh'], explanation: 'Kalimat membandingkan makanan sehat vs tidak sehat dengan hasil berlawanan.' },

  // ── LEVEL 5: SANGAT SULIT (Analisis Teks) + HOT ──
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Bacaan tentang siklus air. Apa yang terjadi setelah air menguap?', answer: 'Membentuk awan', options: ['Menguap lagi', 'Membentuk awan', 'Jadi es', 'Hilang'], explanation: 'Setelah menguap, uap air naik ke atmosfer dan membentuk awan.' },
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Tujuan teks eksposisi tentang pelestarian lingkungan adalah...', answer: 'Memberi informasi', options: ['Menghibur', 'Memberi informasi', 'Menjual produk', 'Menulis cerita'], explanation: 'Teks eksposisi bertujuan memberikan informasi dan pengetahuan.' },
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Ide pokok paragraf tentang pentingnya membaca adalah...', answer: 'Membaca menambah wawasan', options: ['Membaca itu sulit', 'Membaca menambah wawasan', 'Membaca buku mahal', 'Membaca hanya di sekolah'], explanation: 'Ide pokoknya adalah manfaat membaca bagi pengetahuan dan wawasan.' },

  // ── LEVEL 5 HOT: Evaluasi & Sintesis ──
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Bacaan: "Dilarang membuang sampah sembarangan. Denda Rp 500.000." Tujuan teks tersebut adalah...', answer: 'Memberikan peringatan dan aturan', options: ['Menghibur masyarakat', 'Memberikan peringatan dan aturan', 'Menjual produk', 'Memberikan informasi cuaca'], explanation: 'Teks berisi peringatan (dilarang) dan sanksi (denda) merupakan aturan.' },
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Jika sebuah cerita berakhir dengan "Mereka hidup bahagia selamanya", jenis cerita tersebut kemungkinan adalah...', answer: 'Dongeng atau fiksi', options: ['Berita', 'Dongeng atau fiksi', 'Laporan', 'Artikel'], explanation: 'Akhiran "bahagia selamanya" merupakan ciri khas dongeng/fiksi.' },
  { category: 'membaca', subcategory: 'analisis_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Perbedaan utama teks narasi dan teks eksposisi adalah...', answer: 'Narasi bercerita, eksposisi memberi informasi', options: ['Keduanya sama', 'Narasi bercerita, eksposisi memberi informasi', 'Narasi lebih pendek', 'Eksposisi menggunakan gambar'], explanation: 'Teks narasi menceritakan kejadian, teks eksposisi menjelaskan informasi.' },

  // ════════════════════════════════════════════════════════════════
  // LITERASI - MENULIS
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH ──
  { category: 'menulis', subcategory: 'menulis_huruf', type: 'isian', difficulty: 1, question: 'Tulis huruf kapital dari "a":', answer: 'A', explanation: 'Huruf kapital dari "a" adalah "A".' },
  { category: 'menulis', subcategory: 'menulis_huruf', type: 'isian', difficulty: 1, question: 'Tulis huruf kecil dari "G":', answer: 'g', explanation: 'Huruf kecil dari "G" adalah "g".' },
  { category: 'menulis', subcategory: 'menulis_huruf', type: 'pilihan_ganda', difficulty: 1, question: 'Manakah huruf kecil yang benar dari "R"?', answer: 'r', options: ['r', 'v', 'p', 'q'], explanation: 'Huruf kecil dari "R" adalah "r".' },
  { category: 'menulis', subcategory: 'menulis_huruf', type: 'isian', difficulty: 1, question: 'Tulis huruf kapital dari "m":', answer: 'M', explanation: 'Huruf kapital dari "m" adalah "M".' },
  { category: 'menulis', subcategory: 'menulis_huruf', type: 'isian', difficulty: 1, question: 'Tulis huruf kecil dari "D":', answer: 'd', explanation: 'Huruf kecil dari "D" adalah "d".' },

  // ── LEVEL 2: MUDAH ──
  { category: 'menulis', subcategory: 'menulis_kata', type: 'isian', difficulty: 2, question: 'Tulis kata "BUNGA" dengan huruf kecil:', answer: 'bunga', explanation: '"BUNGA" ditulis kecil menjadi "bunga".' },
  { category: 'menulis', subcategory: 'menulis_kata', type: 'isian', difficulty: 2, question: 'Tulis kata "matahari" dengan huruf besar semua:', answer: 'MATAHARI', explanation: '"matahari" ditulis besar semua menjadi "MATAHARI".' },
  { category: 'menulis', subcategory: 'menulis_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Penulisan kata yang benar adalah...', answer: 'Sekolah', options: ['Sekolah', 'sekolah', 'SekoLah', 'SEKOLAH'], explanation: 'Penulisan baku: huruf pertama kapital, sisanya kecil.' },
  { category: 'menulis', subcategory: 'menulis_kata', type: 'isian', difficulty: 2, question: 'Tulis kata "BOLA" dengan huruf kecil:', answer: 'bola', explanation: '"BOLA" ditulis kecil menjadi "bola".' },
  { category: 'menulis', subcategory: 'menulis_kata', type: 'pilihan_ganda', difficulty: 2, question: 'Penulisan yang benar untuk kata "guru" adalah...', answer: 'Guru', options: ['guru', 'Guru', 'GURU', 'GuRu'], explanation: 'Di awal kalimat ditulis dengan huruf kapital: "Guru".' },

  // ── LEVEL 3: SEDANG ──
  { category: 'menulis', subcategory: 'menulis_kalimat', type: 'isian', difficulty: 3, question: 'Buat kalimat sederhana menggunakan kata "kucing":', answer: 'Kucing sedang tidur', options: ['Kucing sedang tidur', 'Buku kucing', 'Meja kucing', 'Kucing biru'], explanation: 'Contoh kalimat yang benar: Kucing sedang tidur.' },
  { category: 'menulis', subcategory: 'menulis_kalimat', type: 'pilihan_ganda', difficulty: 3, question: 'Kalimat yang benar secara tata bahasa adalah...', answer: 'Ibu memasak nasi.', options: ['Ibu memasak nasi.', 'Ibu nasi memasak.', 'Memasak ibu nasi.', 'Nasi ibu memasak.'], explanation: 'Urutan: Subjek (Ibu) + Predikat (memasak) + Objek (nasi).' },
  { category: 'menulis', subcategory: 'tanda_baca', type: 'pilihan_ganda', difficulty: 3, question: 'Tanda baca yang tepat di akhir kalimat tanya adalah...', answer: '?', options: ['.', '?', '!', ','], explanation: 'Kalimat tanya diakhiri dengan tanda tanya "?".' },
  { category: 'menulis', subcategory: 'tanda_baca', type: 'pilihan_ganda', difficulty: 3, question: 'Tanda baca yang tepat di akhir kalimat seru adalah...', answer: '!', options: ['.', '?', '!', ','], explanation: 'Kalimat seru diakhiri dengan tanda seru "!".' },
  { category: 'menulis', subcategory: 'menulis_kalimat', type: 'pilihan_ganda', difficulty: 3, question: 'Kalimat yang menggunakan tanda baca yang benar adalah...', answer: 'Apa kabarmu?', options: ['Apa kabarmu.', 'Apa kabarmu!', 'Apa kabarmu?', 'Apa, kabarmu?'], explanation: 'Kalimat tanya menggunakan tanda tanya "?".' },

  // ── LEVEL 4: SULIT + HOT ──
  { category: 'menulis', subcategory: 'menulis_paragraf', type: 'isian', difficulty: 4, question: 'Buat kalimat tentang aktivitas pagimu (min. 5 kata):', answer: 'Saya bangun pagi lalu sarapan', options: ['Saya bangun pagi lalu sarapan', 'Saya tidur', 'Saya makan', 'Saya bermain'], explanation: 'Kalimat harus lengkap: Saya bangun pagi lalu sarapan sebelum berangkat sekolah.' },
  { category: 'menulis', subcategory: 'ejaan', type: 'pilihan_ganda', difficulty: 4, question: 'Penulisan yang benar adalah...', answer: 'Sayur', options: ['Sayur', 'Sajur', 'Sayoer', 'Sayr'], explanation: 'Penulisan baku: "sayur" atau "Sayur".' },
  { category: 'menulis', subcategory: 'ejaan', type: 'isian', difficulty: 4, question: 'Perbaiki ejaan: "aku pergi kesekolah"', answer: 'Aku pergi ke sekolah', options: ['Aku pergi ke sekolah', 'Aku pergi kesekolah', 'Aku Pergi Ke Sekolah', 'aku pergi ke sekolah'], explanation: 'Yang benar: "Aku pergi ke sekolah." Ada spasi di "ke sekolah".' },
  { category: 'menulis', subcategory: 'ejaan', type: 'pilihan_ganda', difficulty: 4, question: 'Penulisan yang benar untuk "anak-anak" adalah...', answer: 'anak-anak', options: ['anak anak', 'anak-anak', 'anakanak', 'anak–anak'], explanation: 'Kata jamak dengan penghubung pakai tanda hubung "-": anak-anak.' },

  // ── LEVEL 4 HOT: Evaluasi Ejaan ──
  { category: 'menulis', subcategory: 'ejaan', type: 'pilihan_ganda', difficulty: 4, question: 'Kalimat "Dia pergi kepasar membeli buah" ada kesalahan pada...', answer: 'Tidak ada spasi di "ke pasar"', options: ['Tidak ada spasi di "ke pasar"', 'Kata "dia" harus kapital', 'Tidak ada koma', 'Kata "buah" salah'], explanation: 'Yang benar: "Dia pergi ke pasar membeli buah." Perlu spasi setelah "ke".' },

  // ── LEVEL 5: SANGAT SULIT + HOT ──
  { category: 'menulis', subcategory: 'menulis_pendek', type: 'isian', difficulty: 5, question: 'Tulis kalimat saran tentang menjaga kebersihan:', answer: 'Marilah kita menjaga kebersihan lingkungan', options: ['Marilah kita menjaga kebersihan lingkungan', 'Saya suka bersih', 'Kotor itu enak', 'Buang sampah'], explanation: 'Contoh: "Marilah kita menjaga kebersihan lingkungan sekolah."' },
  { category: 'menulis', subcategory: 'struktur_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Paragraf yang baik memiliki...', answer: 'Ide pokok dan kalimat pendukung', options: ['Hanya kalimat', 'Ide pokok dan kalimat pendukung', 'Hanya gambar', 'Banyak titik'], explanation: 'Paragraf yang baik memiliki ide pokok di awal dan diikuti kalimat pendukung.' },

  // ── LEVEL 5 HOT: Evaluasi & Sintesis ──
  { category: 'menulis', subcategory: 'struktur_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Kalimat "Hujan deras mengguyur kota sejak tadi malam. Air mulai menggenang di jalanan." Hubungan kedua kalimat tersebut adalah...', answer: 'Sebab-akibat', options: ['Perbandingan', 'Sebab-akibat', 'Urutan waktu', 'Contoh'], explanation: 'Hujan deras (sebab) → air menggenang (akibat).' },
  { category: 'menulis', subcategory: 'struktur_teks', type: 'pilihan_ganda', difficulty: 5, question: 'Ciri-ciri teks prosedur yang benar adalah...', answer: 'Memiliki tujuan, bahan, dan langkah-langkah', options: ['Memiliki judul saja', 'Memiliki tujuan, bahan, dan langkah-langkah', 'Hanya berisi gambar', 'Berisi puisi'], explanation: 'Teks prosedur berisi: tujuan, bahan/alat, dan langkah-langkah.' },

  // ════════════════════════════════════════════════════════════════
  // NUMERASI - PENJUMLAHAN
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 1, question: '3 + 2 = ?', answer: '5', explanation: '3 + 2 = 5' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 1, question: '5 + 3 = ?', answer: '8', explanation: '5 + 3 = 8' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 1, question: '7 + 1 = ?', answer: '8', explanation: '7 + 1 = 8' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 1, question: '4 + 4 = ?', answer: '8', explanation: '4 + 4 = 8' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 1, question: '6 + 3 = ?', answer: '9', explanation: '6 + 3 = 9' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 1, question: '2 + 5 = ?', answer: '7', options: ['6', '7', '8', '9'], explanation: '2 + 5 = 7' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 1, question: '1 + 9 = ?', answer: '10', options: ['8', '9', '10', '11'], explanation: '1 + 9 = 10' },

  // ── LEVEL 2: MUDAH ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 2, question: '12 + 5 = ?', answer: '17', explanation: '12 + 5 = 17' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 2, question: '15 + 8 = ?', answer: '23', explanation: '15 + 8 = 23' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 2, question: '20 + 15 = ?', answer: '35', options: ['30', '35', '40', '25'], explanation: '20 + 15 = 35' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 2, question: '25 + 13 = ?', answer: '38', explanation: '25 + 13 = 38' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 2, question: '30 + 22 = ?', answer: '52', options: ['42', '52', '51', '53'], explanation: '30 + 22 = 52' },

  // ── LEVEL 3: SEDANG ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 3, question: '45 + 27 = ?', answer: '72', explanation: '45 + 27 = 72' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 3, question: '63 + 38 = ?', answer: '101', explanation: '63 + 38 = 101' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 3, question: '78 + 45 = ?', answer: '123', options: ['122', '123', '124', '125'], explanation: '78 + 45 = 123' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 3, question: '99 + 1 = ?', answer: '100', explanation: '99 + 1 = 100' },

  // ── LEVEL 4: SULIT + HOT ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 4, question: '125 + 87 = ?', answer: '212', options: ['202', '212', '222', '192'], explanation: '125 + 87 = 212' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 4, question: '150 + 275 = ?', answer: '425', explanation: '150 + 275 = 425' },

  // ── LEVEL 4 HOT: Masalah Konteks ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 4, question: 'Andi memiliki 25 kelereng, Budi memiliki 38 kelereng. Berapa jumlah kelereng mereka bersama?', answer: '63', options: ['53', '63', '73', '43'], explanation: '25 + 38 = 63 kelereng.' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 4, question: 'Sebuah perpustakaan memiliki 145 buku cerita dan 187 buku sains. Berapa total buku di perpustakaan?', answer: '332', options: ['322', '332', '342', '312'], explanation: '145 + 187 = 332 buku.' },

  // ── LEVEL 5: SANGAT SULIT + HOT ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 5, question: '250 + 375 = ?', answer: '625', explanation: '250 + 375 = 625' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'isian', difficulty: 5, question: '468 + 542 = ?', answer: '1010', explanation: '468 + 542 = 1010' },

  // ── LEVEL 5 HOT: Pemecahan Masalah ──
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 5, question: 'Ibu membeli 125 kg beras, 78 kg beras lagi di toko. Beras di gudang 200 kg. Berapa total beras seluruhnya?', answer: '403 kg', options: ['303 kg', '403 kg', '503 kg', '393 kg'], explanation: '125 + 78 + 200 = 403 kg beras.' },
  { category: 'berhitung', subcategory: 'penjumlahan', type: 'pilihan_ganda', difficulty: 5, question: 'Sebuah sekolah mengumpulkan 345 kaleng, 278 botol, dan 156 kertas bekas. Berapa total sampah yang terkumpul?', answer: '779', options: ['769', '779', '789', '679'], explanation: '345 + 278 + 156 = 779 sampah.' },

  // ════════════════════════════════════════════════════════════════
  // NUMERASI - PENGURANGAN
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 1, question: '5 - 2 = ?', answer: '3', explanation: '5 - 2 = 3' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 1, question: '8 - 3 = ?', answer: '5', explanation: '8 - 3 = 5' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 1, question: '10 - 4 = ?', answer: '6', explanation: '10 - 4 = 6' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 1, question: '9 - 5 = ?', answer: '4', explanation: '9 - 5 = 4' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 1, question: '7 - 0 = ?', answer: '7', explanation: '7 - 0 = 7' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 1, question: '6 - 1 = ?', answer: '5', options: ['4', '5', '6', '7'], explanation: '6 - 1 = 5' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 1, question: '10 - 7 = ?', answer: '3', options: ['2', '3', '4', '5'], explanation: '10 - 7 = 3' },

  // ── LEVEL 2: MUDAH ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 2, question: '20 - 8 = ?', answer: '12', explanation: '20 - 8 = 12' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 2, question: '25 - 12 = ?', answer: '13', options: ['11', '13', '15', '17'], explanation: '25 - 12 = 13' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 2, question: '30 - 15 = ?', answer: '15', explanation: '30 - 15 = 15' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 2, question: '40 - 18 = ?', answer: '22', options: ['21', '22', '23', '24'], explanation: '40 - 18 = 22' },

  // ── LEVEL 3: SEDANG ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 3, question: '50 - 27 = ?', answer: '23', explanation: '50 - 27 = 23' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 3, question: '73 - 45 = ?', answer: '28', explanation: '73 - 45 = 28' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 3, question: '81 - 36 = ?', answer: '45', options: ['44', '45', '46', '47'], explanation: '81 - 36 = 45' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 3, question: '100 - 55 = ?', answer: '45', explanation: '100 - 55 = 45' },

  // ── LEVEL 4: SULIT + HOT ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 4, question: '200 - 85 = ?', answer: '115', options: ['115', '125', '105', '135'], explanation: '200 - 85 = 115' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 4, question: '350 - 178 = ?', answer: '172', explanation: '350 - 178 = 172' },

  // ── LEVEL 4 HOT: Masalah Konteks ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 4, question: 'Sinta memiliki 85 permen. Ia memberikan 37 permen ke temannya. Berapa sisa permen Sinta?', answer: '48', options: ['38', '48', '58', '42'], explanation: '85 - 37 = 48 permen.' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 4, question: 'Perpustakaan memiliki 250 buku. 86 buku dipinjam siswa. Berapa buku yang tersisa?', answer: '164', options: ['154', '164', '174', '264'], explanation: '250 - 86 = 164 buku.' },

  // ── LEVEL 5: SANGAT SULIT + HOT ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 5, question: '500 - 237 = ?', answer: '263', explanation: '500 - 237 = 263' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'isian', difficulty: 5, question: '1000 - 456 = ?', answer: '544', explanation: '1000 - 456 = 544' },

  // ── LEVEL 5 HOT: Pemecahan Masalah ──
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 5, question: 'Sebuah toko memiliki 500 kg beras. Terjual 187 kg pada Senin dan 156 kg pada Selasa. Berapa sisa beras di toko?', answer: '157 kg', options: ['147 kg', '157 kg', '167 kg', '257 kg'], explanation: '500 - 187 - 156 = 157 kg.' },
  { category: 'berhitung', subcategory: 'pengurangan', type: 'pilihan_ganda', difficulty: 5, question: 'Rina memiliki Rp 50.000. Ia membeli buku Rp 18.500 dan pensil Rp 3.750. Berapa sisa uang Rina?', answer: 'Rp 27.750', options: ['Rp 26.750', 'Rp 27.750', 'Rp 28.750', 'Rp 31.750'], explanation: '50.000 - 18.500 - 3.750 = 27.750.' },

  // ════════════════════════════════════════════════════════════════
  // NUMERASI - PERKALIAN
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 1, question: '2 x 3 = ?', answer: '6', options: ['5', '6', '7', '8'], explanation: '2 x 3 = 6' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 1, question: '4 x 2 = ?', answer: '8', options: ['6', '8', '10', '7'], explanation: '4 x 2 = 8' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 1, question: '5 x 3 = ?', answer: '15', options: ['12', '15', '18', '20'], explanation: '5 x 3 = 15' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 1, question: '3 x 4 = ?', answer: '12', explanation: '3 x 4 = 12' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 1, question: '2 x 5 = ?', answer: '10', explanation: '2 x 5 = 10' },

  // ── LEVEL 2: MUDAH ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 2, question: '6 x 4 = ?', answer: '24', explanation: '6 x 4 = 24' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 2, question: '7 x 5 = ?', answer: '35', options: ['30', '35', '40', '25'], explanation: '7 x 5 = 35' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 2, question: '8 x 3 = ?', answer: '24', explanation: '8 x 3 = 24' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 2, question: '9 x 4 = ?', answer: '36', options: ['32', '36', '40', '27'], explanation: '9 x 4 = 36' },

  // ── LEVEL 3: SEDANG ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 3, question: '8 x 7 = ?', answer: '56', explanation: '8 x 7 = 56' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 3, question: '9 x 6 = ?', answer: '54', explanation: '9 x 6 = 54' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 3, question: '7 x 8 = ?', answer: '56', options: ['48', '54', '56', '63'], explanation: '7 x 8 = 56' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 3, question: '9 x 9 = ?', answer: '81', explanation: '9 x 9 = 81' },

  // ── LEVEL 4: SULIT + HOT ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 4, question: '12 x 8 = ?', answer: '96', options: ['88', '96', '104', '84'], explanation: '12 x 8 = 96' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 4, question: '15 x 6 = ?', answer: '90', explanation: '15 x 6 = 90' },

  // ── LEVEL 4 HOT: Masalah Konteks ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 4, question: 'Di kelas ada 5 baris kursi, setiap baris 6 kursi. Berapa total kursi di kelas?', answer: '30', options: ['25', '30', '35', '11'], explanation: '5 x 6 = 30 kursi.' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 4, question: 'Andi membeli 4 kotak pensil. Setiap kotak berisi 12 pensil. Berapa total pensil Andi?', answer: '48', options: ['36', '48', '16', '44'], explanation: '4 x 12 = 48 pensil.' },

  // ── LEVEL 5: SANGAT SULIT + HOT ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 5, question: '15 x 9 = ?', answer: '135', explanation: '15 x 9 = 135' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'isian', difficulty: 5, question: '24 x 5 = ?', answer: '120', explanation: '24 x 5 = 120' },

  // ── LEVEL 5 HOT: Pemecahan Masalah ──
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 5, question: 'Sebuah sekolah mengadakan lomba. Ada 8 kelas, setiap kelas mengirim 15 siswa. Setiap siswa membuat 3 karya. Berapa total karya yang dikumpulkan?', answer: '360', options: ['240', '360', '480', '120'], explanation: '8 x 15 x 3 = 360 karya.' },
  { category: 'berhitung', subcategory: 'perkalian', type: 'pilihan_ganda', difficulty: 5, question: 'Pak Budi memiliki 6 ayam. Setiap ayam bertelur 4 butir per hari. Berapa telur yang terkumpul dalam 1 minggu?', answer: '168', options: ['144', '168', '24', '84'], explanation: '6 x 4 x 7 = 168 telur.' },

  // ════════════════════════════════════════════════════════════════
  // NUMERASI - PEMBAGIAN
  // ════════════════════════════════════════════════════════════════

  // ── LEVEL 1: SANGAT MUDAH ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 1, question: '6 : 2 = ?', answer: '3', options: ['2', '3', '4', '5'], explanation: '6 : 2 = 3' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 1, question: '8 : 4 = ?', answer: '2', options: ['1', '2', '3', '4'], explanation: '8 : 4 = 2' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 1, question: '10 : 5 = ?', answer: '2', options: ['1', '2', '3', '5'], explanation: '10 : 5 = 2' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 1, question: '9 : 3 = ?', answer: '3', explanation: '9 : 3 = 3' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 1, question: '12 : 4 = ?', answer: '3', explanation: '12 : 4 = 3' },

  // ── LEVEL 2: MUDAH ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 2, question: '12 : 3 = ?', answer: '4', explanation: '12 : 3 = 4' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 2, question: '20 : 5 = ?', answer: '4', explanation: '20 : 5 = 4' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 2, question: '24 : 6 = ?', answer: '4', options: ['3', '4', '5', '6'], explanation: '24 : 6 = 4' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 2, question: '18 : 3 = ?', answer: '6', explanation: '18 : 3 = 6' },

  // ── LEVEL 3: SEDANG ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 3, question: '45 : 9 = ?', answer: '5', explanation: '45 : 9 = 5' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 3, question: '56 : 7 = ?', answer: '8', explanation: '56 : 7 = 8' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 3, question: '63 : 9 = ?', answer: '7', options: ['6', '7', '8', '9'], explanation: '63 : 9 = 7' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 3, question: '72 : 8 = ?', answer: '9', explanation: '72 : 8 = 9' },

  // ── LEVEL 4: SULIT + HOT ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 4, question: '96 : 8 = ?', answer: '12', options: ['10', '11', '12', '13'], explanation: '96 : 8 = 12' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 4, question: '120 : 6 = ?', answer: '20', explanation: '120 : 6 = 20' },

  // ── LEVEL 4 HOT: Masalah Konteks ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 4, question: '30 kue akan dibagikan ke 5 anak secara adil. Berapa kue yang diterima setiap anak?', answer: '6', options: ['5', '6', '7', '8'], explanation: '30 : 5 = 6 kue per anak.' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 4, question: 'Pak Guru memiliki 48 pensil yang akan dibagikan ke 8 murid. Berapa pensil untuk setiap murid?', answer: '6', options: ['5', '6', '7', '8'], explanation: '48 : 8 = 6 pensil per murid.' },

  // ── LEVEL 5: SANGAT SULIT + HOT ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 5, question: '135 : 9 = ?', answer: '15', explanation: '135 : 9 = 15' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'isian', difficulty: 5, question: '144 : 12 = ?', answer: '12', explanation: '144 : 12 = 12' },

  // ── LEVEL 5 HOT: Pemecahan Masalah ──
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 5, question: 'Sebuah pabrik menghasilkan 720 botol minuman dalam 8 jam. Berapa botol yang dihasilkan per jam?', answer: '90', options: ['80', '90', '100', '70'], explanation: '720 : 8 = 90 botol per jam.' },
  { category: 'berhitung', subcategory: 'pembagian', type: 'pilihan_ganda', difficulty: 5, question: 'Ibu membeli 3 lusin telur. Jika dijual ke 4 orang secara adil, berapa telur yang diterima setiap orang? (1 lusin = 12)', answer: '9', options: ['8', '9', '10', '12'], explanation: '3 x 12 = 36 telur. 36 : 4 = 9 telur per orang.' },



  // === SOAL TAMBAHAN (Ide Pokok & Informasi Penting) ===
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Kelinci Kesayangan Budi] Ide pokok paragraf 1 dan informasi penting.","answer":"Budi memiliki kelinci peliharaan bernama Putih.","options":null,"explanation":"Teks: Kelinci Kesayangan Budi. Budi memiliki kelinci peliharaan bernama Putih."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Kelinci Kesayangan Budi] Ide pokok paragraf 2 dan informasi penting.","answer":"Budi rajin memberi makan Putih setiap pagi.","options":null,"explanation":"Teks: Kelinci Kesayangan Budi. Budi rajin memberi makan Putih setiap pagi."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Kelinci Kesayangan Budi] Ide pokok paragraf 3 dan informasi penting.","answer":"Budi rutin membersihkan kandang kelincinya.","options":null,"explanation":"Teks: Kelinci Kesayangan Budi. Budi rutin membersihkan kandang kelincinya."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Kelinci Kesayangan Budi] Ide pokok paragraf 4 dan informasi penting.","answer":"Budi mengajak Putih bermain di taman saat hari libur.","options":null,"explanation":"Teks: Kelinci Kesayangan Budi. Budi mengajak Putih bermain di taman saat hari libur."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Kelinci Kesayangan Budi] Ide pokok paragraf terakhir dan informasi penting.","answer":"Budi sangat menyayangi kelincinya dengan cara memberi makan, membersihkan kandang, dan mengajaknya bermain.","options":null,"explanation":"Teks: Kelinci Kesayangan Budi. Budi sangat menyayangi kelincinya dengan cara memberi makan, membersihkan kandang, dan mengajaknya bermain."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Liburan di Rumah Nenek] Ide pokok paragraf 1 dan informasi penting.","answer":"Rina berlibur ke rumah neneknya di desa.","options":null,"explanation":"Teks: Liburan di Rumah Nenek. Rina berlibur ke rumah neneknya di desa."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Liburan di Rumah Nenek] Ide pokok paragraf 2 dan informasi penting.","answer":"Nenek memiliki kebun sayur yang luas di belakang rumah.","options":null,"explanation":"Teks: Liburan di Rumah Nenek. Nenek memiliki kebun sayur yang luas di belakang rumah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Liburan di Rumah Nenek] Ide pokok paragraf 3 dan informasi penting.","answer":"Rina membantu nenek memanen sayuran di kebun.","options":null,"explanation":"Teks: Liburan di Rumah Nenek. Rina membantu nenek memanen sayuran di kebun."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Liburan di Rumah Nenek] Ide pokok paragraf 4 dan informasi penting.","answer":"Nenek memasak sayuran hasil panen untuk makan siang.","options":null,"explanation":"Teks: Liburan di Rumah Nenek. Nenek memasak sayuran hasil panen untuk makan siang."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Liburan di Rumah Nenek] Ide pokok paragraf terakhir dan informasi penting.","answer":"Kegiatan seru Rina saat liburan di desa adalah membantu nenek di kebun sayur.","options":null,"explanation":"Teks: Liburan di Rumah Nenek. Kegiatan seru Rina saat liburan di desa adalah membantu nenek di kebun sayur."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Kerja Bakti di Sekolah] Ide pokok paragraf 1 dan informasi penting.","answer":"SD Kusuma Bangsa mengadakan kegiatan kerja bakti rutin.","options":null,"explanation":"Teks: Manfaat Kerja Bakti di Sekolah. SD Kusuma Bangsa mengadakan kegiatan kerja bakti rutin."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Kerja Bakti di Sekolah] Ide pokok paragraf 2 dan informasi penting.","answer":"Pembagian tugas kebersihan untuk setiap kelas.","options":null,"explanation":"Teks: Manfaat Kerja Bakti di Sekolah. Pembagian tugas kebersihan untuk setiap kelas."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Kerja Bakti di Sekolah] Ide pokok paragraf 3 dan informasi penting.","answer":"Manfaat kerja bakti untuk kenyamanan dan kesehatan lingkungan sekolah.","options":null,"explanation":"Teks: Manfaat Kerja Bakti di Sekolah. Manfaat kerja bakti untuk kenyamanan dan kesehatan lingkungan sekolah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Kerja Bakti di Sekolah] Ide pokok paragraf 4 dan informasi penting.","answer":"Kerja bakti melatih kerukunan dan kerja sama antar siswa.","options":null,"explanation":"Teks: Manfaat Kerja Bakti di Sekolah. Kerja bakti melatih kerukunan dan kerja sama antar siswa."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Manfaat Kerja Bakti di Sekolah] Ide pokok paragraf terakhir dan informasi penting.","answer":"Kerja bakti di sekolah penting dilakukan agar lingkungan bersih, sehat, dan siswa semakin rukun.","options":null,"explanation":"Teks: Manfaat Kerja Bakti di Sekolah. Kerja bakti di sekolah penting dilakukan agar lingkungan bersih, sehat, dan siswa semakin rukun."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berolahraga Pagi] Ide pokok paragraf 1 dan informasi penting.","answer":"Olahraga pagi adalah kebiasaan yang baik untuk tubuh.","options":null,"explanation":"Teks: Berolahraga Pagi. Olahraga pagi adalah kebiasaan yang baik untuk tubuh."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berolahraga Pagi] Ide pokok paragraf 2 dan informasi penting.","answer":"Jenis-jenis olahraga ringan yang bisa dilakukan di pagi hari.","options":null,"explanation":"Teks: Berolahraga Pagi. Jenis-jenis olahraga ringan yang bisa dilakukan di pagi hari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berolahraga Pagi] Ide pokok paragraf 3 dan informasi penting.","answer":"Manfaat olahraga pagi untuk kesehatan dan kebugaran fisik.","options":null,"explanation":"Teks: Berolahraga Pagi. Manfaat olahraga pagi untuk kesehatan dan kebugaran fisik."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berolahraga Pagi] Ide pokok paragraf 4 dan informasi penting.","answer":"Manfaat olahraga pagi untuk pikiran dan semangat.","options":null,"explanation":"Teks: Berolahraga Pagi. Manfaat olahraga pagi untuk pikiran dan semangat."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Berolahraga Pagi] Ide pokok paragraf terakhir dan informasi penting.","answer":"Berolahraga pagi secara rutin sangat penting karena menyehatkan fisik dan menyegarkan pikiran.","options":null,"explanation":"Teks: Berolahraga Pagi. Berolahraga pagi secara rutin sangat penting karena menyehatkan fisik dan menyegarkan pikiran."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Daur Hidup Kupu-kupu] Ide pokok paragraf 1 dan informasi penting.","answer":"Kupu-kupu mengalami proses metamorfosis sempurna.","options":null,"explanation":"Teks: Daur Hidup Kupu-kupu. Kupu-kupu mengalami proses metamorfosis sempurna."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Daur Hidup Kupu-kupu] Ide pokok paragraf 2 dan informasi penting.","answer":"Tahap pertama daur hidup kupu-kupu dimulai dari telur.","options":null,"explanation":"Teks: Daur Hidup Kupu-kupu. Tahap pertama daur hidup kupu-kupu dimulai dari telur."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Daur Hidup Kupu-kupu] Ide pokok paragraf 3 dan informasi penting.","answer":"Telur menetas menjadi ulat (larva) yang sangat suka makan daun.","options":null,"explanation":"Teks: Daur Hidup Kupu-kupu. Telur menetas menjadi ulat (larva) yang sangat suka makan daun."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Daur Hidup Kupu-kupu] Ide pokok paragraf 4 dan informasi penting.","answer":"Ulat berubah menjadi kepompong (pupa) sebelum akhirnya menjadi kupu-kupu dewasa.","options":null,"explanation":"Teks: Daur Hidup Kupu-kupu. Ulat berubah menjadi kepompong (pupa) sebelum akhirnya menjadi kupu-kupu dewasa."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty":5,"question":"[Daur Hidup Kupu-kupu] Ide pokok paragraf terakhir dan informasi penting.","answer":"Daur hidup kupu-kupu terdiri dari empat tahap, yaitu telur, ulat, kepompong, dan kupu-kupu dewasa.","options":null,"explanation":"Teks: Daur Hidup Kupu-kupu. Daur hidup kupu-kupu terdiri dari empat tahap, yaitu telur, ulat, kepompong, dan kupu-kupu dewasa."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kelestarian Hutan] Ide pokok paragraf 1 dan informasi penting.","answer":"Hutan berperan penting sebagai paru-paru dunia penyedia oksigen.","options":null,"explanation":"Teks: Menjaga Kelestarian Hutan. Hutan berperan penting sebagai paru-paru dunia penyedia oksigen."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kelestarian Hutan] Ide pokok paragraf 2 dan informasi penting.","answer":"Hutan adalah habitat asli bagi berbagai jenis satwa dan tumbuhan.","options":null,"explanation":"Teks: Menjaga Kelestarian Hutan. Hutan adalah habitat asli bagi berbagai jenis satwa dan tumbuhan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kelestarian Hutan] Ide pokok paragraf 3 dan informasi penting.","answer":"Kelestarian hutan terancam oleh tindakan penebangan liar dan pembakaran hutan.","options":null,"explanation":"Teks: Menjaga Kelestarian Hutan. Kelestarian hutan terancam oleh tindakan penebangan liar dan pembakaran hutan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kelestarian Hutan] Ide pokok paragraf 4 dan informasi penting.","answer":"Upaya pelestarian hutan harus segera dilakukan melalui reboisasi dan tindakan tegas.","options":null,"explanation":"Teks: Menjaga Kelestarian Hutan. Upaya pelestarian hutan harus segera dilakukan melalui reboisasi dan tindakan tegas."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Menjaga Kelestarian Hutan] Ide pokok paragraf terakhir dan informasi penting.","answer":"Hutan harus dilestarikan karena merupakan sumber oksigen dan tempat tinggal satwa yang kini terancam rusak oleh manusia.","options":null,"explanation":"Teks: Menjaga Kelestarian Hutan. Hutan harus dilestarikan karena merupakan sumber oksigen dan tempat tinggal satwa yang kini terancam rusak oleh manusia."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membantu Ibu Memasak] Ide pokok paragraf 1 dan informasi penting.","answer":"Siti membantu ibu memasak sup ayam di dapur.","options":null,"explanation":"Teks: Membantu Ibu Memasak. Siti membantu ibu memasak sup ayam di dapur."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membantu Ibu Memasak] Ide pokok paragraf 2 dan informasi penting.","answer":"Siti bertugas mengupas dan mencuci sayuran.","options":null,"explanation":"Teks: Membantu Ibu Memasak. Siti bertugas mengupas dan mencuci sayuran."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membantu Ibu Memasak] Ide pokok paragraf 3 dan informasi penting.","answer":"Ibu memotong sayuran dan merebus daging ayam.","options":null,"explanation":"Teks: Membantu Ibu Memasak. Ibu memotong sayuran dan merebus daging ayam."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membantu Ibu Memasak] Ide pokok paragraf 4 dan informasi penting.","answer":"Sup ayam sudah matang dan siap disajikan untuk sarapan.","options":null,"explanation":"Teks: Membantu Ibu Memasak. Sup ayam sudah matang dan siap disajikan untuk sarapan."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Membantu Ibu Memasak] Ide pokok paragraf terakhir dan informasi penting.","answer":"Siti dan Ibu bekerja sama memasak sup ayam yang lezat untuk sarapan keluarga.","options":null,"explanation":"Teks: Membantu Ibu Memasak. Siti dan Ibu bekerja sama memasak sup ayam yang lezat untuk sarapan keluarga."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Bermain Layang-layang] Ide pokok paragraf 1 dan informasi penting.","answer":"Andi pergi ke lapangan membawa layang-layang baru.","options":null,"explanation":"Teks: Bermain Layang-layang. Andi pergi ke lapangan membawa layang-layang baru."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Bermain Layang-layang] Ide pokok paragraf 2 dan informasi penting.","answer":"Andi menerbangkan layang-layangnya karena angin bertiup kencang.","options":null,"explanation":"Teks: Bermain Layang-layang. Andi menerbangkan layang-layangnya karena angin bertiup kencang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Bermain Layang-layang] Ide pokok paragraf 3 dan informasi penting.","answer":"Layang-layang Andi terbang sangat tinggi dan tampak indah.","options":null,"explanation":"Teks: Bermain Layang-layang. Layang-layang Andi terbang sangat tinggi dan tampak indah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Bermain Layang-layang] Ide pokok paragraf 4 dan informasi penting.","answer":"Andi dan anak-anak lainnya pulang saat menjelang magrib.","options":null,"explanation":"Teks: Bermain Layang-layang. Andi dan anak-anak lainnya pulang saat menjelang magrib."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Bermain Layang-layang] Ide pokok paragraf terakhir dan informasi penting.","answer":"Andi merasa gembira bisa menerbangkan layang-layang barunya tinggi-tinggi di lapangan pada sore hari.","options":null,"explanation":"Teks: Bermain Layang-layang. Andi merasa gembira bisa menerbangkan layang-layang barunya tinggi-tinggi di lapangan pada sore hari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menabung di Celengan] Ide pokok paragraf 1 dan informasi penting.","answer":"Doni memiliki celengan tanah liat berbentuk ayam jago.","options":null,"explanation":"Teks: Menabung di Celengan. Doni memiliki celengan tanah liat berbentuk ayam jago."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menabung di Celengan] Ide pokok paragraf 2 dan informasi penting.","answer":"Doni rajin menyisihkan uang sakunya untuk ditabung setiap hari.","options":null,"explanation":"Teks: Menabung di Celengan. Doni rajin menyisihkan uang sakunya untuk ditabung setiap hari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menabung di Celengan] Ide pokok paragraf 3 dan informasi penting.","answer":"Tujuan Doni menabung adalah untuk membeli sepatu sekolah baru.","options":null,"explanation":"Teks: Menabung di Celengan. Tujuan Doni menabung adalah untuk membeli sepatu sekolah baru."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menabung di Celengan] Ide pokok paragraf 4 dan informasi penting.","answer":"Celengan Doni dipecahkan dan uangnya cukup untuk membeli sepatu.","options":null,"explanation":"Teks: Menabung di Celengan. Celengan Doni dipecahkan dan uangnya cukup untuk membeli sepatu."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Menabung di Celengan] Ide pokok paragraf terakhir dan informasi penting.","answer":"Kebiasaan berhemat dan menabung membuat Doni bisa membeli sepatu baru secara mandiri.","options":null,"explanation":"Teks: Menabung di Celengan. Kebiasaan berhemat dan menabung membuat Doni bisa membeli sepatu baru secara mandiri."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Merawat Tanaman Hias] Ide pokok paragraf 1 dan informasi penting.","answer":"Ibu memelihara tanaman hias yang membuat rumah menjadi asri.","options":null,"explanation":"Teks: Merawat Tanaman Hias. Ibu memelihara tanaman hias yang membuat rumah menjadi asri."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Merawat Tanaman Hias] Ide pokok paragraf 2 dan informasi penting.","answer":"Lani membantu ibu menyiram tanaman setiap sore.","options":null,"explanation":"Teks: Merawat Tanaman Hias. Lani membantu ibu menyiram tanaman setiap sore."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Merawat Tanaman Hias] Ide pokok paragraf 3 dan informasi penting.","answer":"Ibu memberikan pupuk agar tanaman tumbuh subur dan berbunga indah.","options":null,"explanation":"Teks: Merawat Tanaman Hias. Ibu memberikan pupuk agar tanaman tumbuh subur dan berbunga indah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Merawat Tanaman Hias] Ide pokok paragraf 4 dan informasi penting.","answer":"Lani membersihkan daun-daun kering dari tanaman.","options":null,"explanation":"Teks: Merawat Tanaman Hias. Lani membersihkan daun-daun kering dari tanaman."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Merawat Tanaman Hias] Ide pokok paragraf terakhir dan informasi penting.","answer":"Tanaman hias di rumah akan tumbuh subur, segar, dan berbunga indah jika rutin disiram dan dipupuk.","options":null,"explanation":"Teks: Merawat Tanaman Hias. Tanaman hias di rumah akan tumbuh subur, segar, dan berbunga indah jika rutin disiram dan dipupuk."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pergi ke Kebun Binatang] Ide pokok paragraf 1 dan informasi penting.","answer":"Keluarga Edo pergi berwisata ke kebun binatang pada hari Minggu.","options":null,"explanation":"Teks: Pergi ke Kebun Binatang. Keluarga Edo pergi berwisata ke kebun binatang pada hari Minggu."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pergi ke Kebun Binatang] Ide pokok paragraf 2 dan informasi penting.","answer":"Edo melihat gajah berbadan besar yang sedang menyemprotkan air.","options":null,"explanation":"Teks: Pergi ke Kebun Binatang. Edo melihat gajah berbadan besar yang sedang menyemprotkan air."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pergi ke Kebun Binatang] Ide pokok paragraf 3 dan informasi penting.","answer":"Edo melihat dan memberi makan jerapah yang berleher panjang.","options":null,"explanation":"Teks: Pergi ke Kebun Binatang. Edo melihat dan memberi makan jerapah yang berleher panjang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pergi ke Kebun Binatang] Ide pokok paragraf 4 dan informasi penting.","answer":"Edo merasa lelah tetapi sangat bahagia saat pulang.","options":null,"explanation":"Teks: Pergi ke Kebun Binatang. Edo merasa lelah tetapi sangat bahagia saat pulang."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pergi ke Kebun Binatang] Ide pokok paragraf terakhir dan informasi penting.","answer":"Berwisata ke kebun binatang memberikan pengalaman menyenangkan bagi Edo karena bisa melihat dan berinteraksi dengan hewan.","options":null,"explanation":"Teks: Pergi ke Kebun Binatang. Berwisata ke kebun binatang memberikan pengalaman menyenangkan bagi Edo karena bisa melihat dan berinteraksi dengan hewan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Sarapan Pagi] Ide pokok paragraf 1 dan informasi penting.","answer":"Sarapan pagi sangat penting untuk memberikan energi bagi tubuh.","options":null,"explanation":"Teks: Pentingnya Sarapan Pagi. Sarapan pagi sangat penting untuk memberikan energi bagi tubuh."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Sarapan Pagi] Ide pokok paragraf 2 dan informasi penting.","answer":"Ibu Dina rajin menyiapkan sarapan bergizi setiap hari.","options":null,"explanation":"Teks: Pentingnya Sarapan Pagi. Ibu Dina rajin menyiapkan sarapan bergizi setiap hari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Sarapan Pagi] Ide pokok paragraf 3 dan informasi penting.","answer":"Anak yang sarapan akan lebih mudah berkonsentrasi belajar di sekolah.","options":null,"explanation":"Teks: Pentingnya Sarapan Pagi. Anak yang sarapan akan lebih mudah berkonsentrasi belajar di sekolah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Sarapan Pagi] Ide pokok paragraf 4 dan informasi penting.","answer":"Melewatkan sarapan bisa membuat anak lemas, mengantuk, dan sakit perut.","options":null,"explanation":"Teks: Pentingnya Sarapan Pagi. Melewatkan sarapan bisa membuat anak lemas, mengantuk, dan sakit perut."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pentingnya Sarapan Pagi] Ide pokok paragraf terakhir dan informasi penting.","answer":"Sarapan pagi sangat penting dilakukan sebelum sekolah agar tubuh bertenaga dan mudah konsentrasi belajar.","options":null,"explanation":"Teks: Pentingnya Sarapan Pagi. Sarapan pagi sangat penting dilakukan sebelum sekolah agar tubuh bertenaga dan mudah konsentrasi belajar."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membersihkan Kamar Tidur] Ide pokok paragraf 1 dan informasi penting.","answer":"Ayu adalah anak mandiri yang selalu membersihkan kamarnya sendiri.","options":null,"explanation":"Teks: Membersihkan Kamar Tidur. Ayu adalah anak mandiri yang selalu membersihkan kamarnya sendiri."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membersihkan Kamar Tidur] Ide pokok paragraf 2 dan informasi penting.","answer":"Ayu melipat selimut dan merapikan bantal guling.","options":null,"explanation":"Teks: Membersihkan Kamar Tidur. Ayu melipat selimut dan merapikan bantal guling."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membersihkan Kamar Tidur] Ide pokok paragraf 3 dan informasi penting.","answer":"Ayu menyapu lantai kamar agar bersih dan nyaman.","options":null,"explanation":"Teks: Membersihkan Kamar Tidur. Ayu menyapu lantai kamar agar bersih dan nyaman."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membersihkan Kamar Tidur] Ide pokok paragraf 4 dan informasi penting.","answer":"Ibu bangga kepada Ayu yang rajin dan menjadikannya contoh untuk adiknya.","options":null,"explanation":"Teks: Membersihkan Kamar Tidur. Ibu bangga kepada Ayu yang rajin dan menjadikannya contoh untuk adiknya."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Membersihkan Kamar Tidur] Ide pokok paragraf terakhir dan informasi penting.","answer":"Mandiri membersihkan tempat tidur dan menyapu lantai membuat kamar selalu bersih dan nyaman ditempati.","options":null,"explanation":"Teks: Membersihkan Kamar Tidur. Mandiri membersihkan tempat tidur dan menyapu lantai membuat kamar selalu bersih dan nyaman ditempati."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membaca Buku Cerita] Ide pokok paragraf 1 dan informasi penting.","answer":"Dika memiliki hobi membaca buku cerita bergambar.","options":null,"explanation":"Teks: Membaca Buku Cerita. Dika memiliki hobi membaca buku cerita bergambar."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membaca Buku Cerita] Ide pokok paragraf 2 dan informasi penting.","answer":"Dika selalu membaca buku pada waktu luang.","options":null,"explanation":"Teks: Membaca Buku Cerita. Dika selalu membaca buku pada waktu luang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membaca Buku Cerita] Ide pokok paragraf 3 dan informasi penting.","answer":"Membaca buku membuat ilmu, pengetahuan, dan wawasan Dika bertambah luas.","options":null,"explanation":"Teks: Membaca Buku Cerita. Membaca buku membuat ilmu, pengetahuan, dan wawasan Dika bertambah luas."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Membaca Buku Cerita] Ide pokok paragraf 4 dan informasi penting.","answer":"Dika sering membagikan cerita dari buku kepada teman-temannya di sekolah.","options":null,"explanation":"Teks: Membaca Buku Cerita. Dika sering membagikan cerita dari buku kepada teman-temannya di sekolah."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Membaca Buku Cerita] Ide pokok paragraf terakhir dan informasi penting.","answer":"Gemar membaca buku cerita memiliki banyak manfaat, seperti memperluas pengetahuan dan membuat kita menjadi anak yang pintar.","options":null,"explanation":"Teks: Membaca Buku Cerita. Gemar membaca buku cerita memiliki banyak manfaat, seperti memperluas pengetahuan dan membuat kita menjadi anak yang pintar."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Sayuran bagi Tubuh] Ide pokok paragraf 1 dan informasi penting.","answer":"Sayuran hijau mengandung gizi yang sangat penting bagi kesehatan tubuh.","options":null,"explanation":"Teks: Manfaat Sayuran bagi Tubuh. Sayuran hijau mengandung gizi yang sangat penting bagi kesehatan tubuh."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Sayuran bagi Tubuh] Ide pokok paragraf 2 dan informasi penting.","answer":"Manfaat wortel yang kaya vitamin A untuk kesehatan mata.","options":null,"explanation":"Teks: Manfaat Sayuran bagi Tubuh. Manfaat wortel yang kaya vitamin A untuk kesehatan mata."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Sayuran bagi Tubuh] Ide pokok paragraf 3 dan informasi penting.","answer":"Manfaat bayam yang kaya zat besi dan kalsium untuk tulang dan darah.","options":null,"explanation":"Teks: Manfaat Sayuran bagi Tubuh. Manfaat bayam yang kaya zat besi dan kalsium untuk tulang dan darah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Sayuran bagi Tubuh] Ide pokok paragraf 4 dan informasi penting.","answer":"Anak-anak harus membiasakan diri makan sayur karena sangat bermanfaat.","options":null,"explanation":"Teks: Manfaat Sayuran bagi Tubuh. Anak-anak harus membiasakan diri makan sayur karena sangat bermanfaat."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Manfaat Sayuran bagi Tubuh] Ide pokok paragraf terakhir dan informasi penting.","answer":"Rutin mengonsumsi sayuran seperti wortel dan bayam sangat penting untuk menjaga kesehatan organ tubuh, mata, dan tulang.","options":null,"explanation":"Teks: Manfaat Sayuran bagi Tubuh. Rutin mengonsumsi sayuran seperti wortel dan bayam sangat penting untuk menjaga kesehatan organ tubuh, mata, dan tulang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berkunjung ke Perpustakaan Daerah] Ide pokok paragraf 1 dan informasi penting.","answer":"Kunjungan siswa kelas tiga ke perpustakaan daerah untuk menumbuhkan minat baca.","options":null,"explanation":"Teks: Berkunjung ke Perpustakaan Daerah. Kunjungan siswa kelas tiga ke perpustakaan daerah untuk menumbuhkan minat baca."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berkunjung ke Perpustakaan Daerah] Ide pokok paragraf 2 dan informasi penting.","answer":"Suasana perpustakaan daerah yang tenang dan tertata rapi.","options":null,"explanation":"Teks: Berkunjung ke Perpustakaan Daerah. Suasana perpustakaan daerah yang tenang dan tertata rapi."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berkunjung ke Perpustakaan Daerah] Ide pokok paragraf 3 dan informasi penting.","answer":"Ruangan khusus anak-anak yang memiliki banyak koleksi buku cerita dan ensiklopedia.","options":null,"explanation":"Teks: Berkunjung ke Perpustakaan Daerah. Ruangan khusus anak-anak yang memiliki banyak koleksi buku cerita dan ensiklopedia."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Berkunjung ke Perpustakaan Daerah] Ide pokok paragraf 4 dan informasi penting.","answer":"Petugas perpustakaan mengajarkan cara meminjam dan mengembalikan buku.","options":null,"explanation":"Teks: Berkunjung ke Perpustakaan Daerah. Petugas perpustakaan mengajarkan cara meminjam dan mengembalikan buku."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Berkunjung ke Perpustakaan Daerah] Ide pokok paragraf terakhir dan informasi penting.","answer":"Perpustakaan daerah menyediakan ruangan nyaman dan buku yang beragam untuk meningkatkan minat baca pengunjung, termasuk anak-anak.","options":null,"explanation":"Teks: Berkunjung ke Perpustakaan Daerah. Perpustakaan daerah menyediakan ruangan nyaman dan buku yang beragam untuk meningkatkan minat baca pengunjung, termasuk anak-anak."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Akibat Membuang Sampah Sembarangan] Ide pokok paragraf 1 dan informasi penting.","answer":"Kebiasaan buruk membuang sampah sembarangan masih sering dilakukan banyak orang.","options":null,"explanation":"Teks: Akibat Membuang Sampah Sembarangan. Kebiasaan buruk membuang sampah sembarangan masih sering dilakukan banyak orang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Akibat Membuang Sampah Sembarangan] Ide pokok paragraf 2 dan informasi penting.","answer":"Sampah yang berserakan merusak keindahan lingkungan dan menimbulkan bau tidak sedap.","options":null,"explanation":"Teks: Akibat Membuang Sampah Sembarangan. Sampah yang berserakan merusak keindahan lingkungan dan menimbulkan bau tidak sedap."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Akibat Membuang Sampah Sembarangan] Ide pokok paragraf 3 dan informasi penting.","answer":"Sampah yang menyumbat aliran air dapat menyebabkan bencana banjir.","options":null,"explanation":"Teks: Akibat Membuang Sampah Sembarangan. Sampah yang menyumbat aliran air dapat menyebabkan bencana banjir."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Akibat Membuang Sampah Sembarangan] Ide pokok paragraf 4 dan informasi penting.","answer":"Kita harus disiplin membuang sampah pada tempatnya demi lingkungan yang sehat.","options":null,"explanation":"Teks: Akibat Membuang Sampah Sembarangan. Kita harus disiplin membuang sampah pada tempatnya demi lingkungan yang sehat."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Akibat Membuang Sampah Sembarangan] Ide pokok paragraf terakhir dan informasi penting.","answer":"Membuang sampah sembarangan merugikan karena menyebabkan lingkungan kotor, bau, dan memicu banjir, sehingga kita harus disiplin menjaga kebersihan.","options":null,"explanation":"Teks: Akibat Membuang Sampah Sembarangan. Membuang sampah sembarangan merugikan karena menyebabkan lingkungan kotor, bau, dan memicu banjir, sehingga kita harus disiplin menjaga kebersihan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Belajar Kelompok di Rumah Rio] Ide pokok paragraf 1 dan informasi penting.","answer":"Bima, Edo, dan Rio berkumpul untuk mengerjakan tugas kesenian membuat kerajinan dari bahan bekas.","options":null,"explanation":"Teks: Belajar Kelompok di Rumah Rio. Bima, Edo, dan Rio berkumpul untuk mengerjakan tugas kesenian membuat kerajinan dari bahan bekas."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Belajar Kelompok di Rumah Rio] Ide pokok paragraf 2 dan informasi penting.","answer":"Mereka saling membagi tugas dalam membuat pot dari botol bekas.","options":null,"explanation":"Teks: Belajar Kelompok di Rumah Rio. Mereka saling membagi tugas dalam membuat pot dari botol bekas."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Belajar Kelompok di Rumah Rio] Ide pokok paragraf 3 dan informasi penting.","answer":"Kerja sama membuat tugas terasa ringan dan suasana belajar kelompok menjadi rukun.","options":null,"explanation":"Teks: Belajar Kelompok di Rumah Rio. Kerja sama membuat tugas terasa ringan dan suasana belajar kelompok menjadi rukun."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Belajar Kelompok di Rumah Rio] Ide pokok paragraf 4 dan informasi penting.","answer":"Mereka menikmati camilan dari ibu Rio setelah kerajinan pot bunga selesai dibuat.","options":null,"explanation":"Teks: Belajar Kelompok di Rumah Rio. Mereka menikmati camilan dari ibu Rio setelah kerajinan pot bunga selesai dibuat."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Belajar Kelompok di Rumah Rio] Ide pokok paragraf terakhir dan informasi penting.","answer":"Belajar kelompok dengan cara membagi tugas dan bekerja sama membuat pekerjaan cepat selesai dengan hasil memuaskan.","options":null,"explanation":"Teks: Belajar Kelompok di Rumah Rio. Belajar kelompok dengan cara membagi tugas dan bekerja sama membuat pekerjaan cepat selesai dengan hasil memuaskan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kesehatan Gigi] Ide pokok paragraf 1 dan informasi penting.","answer":"Pentingnya menjaga kesehatan gigi untuk membantu mengunyah makanan.","options":null,"explanation":"Teks: Menjaga Kesehatan Gigi. Pentingnya menjaga kesehatan gigi untuk membantu mengunyah makanan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kesehatan Gigi] Ide pokok paragraf 2 dan informasi penting.","answer":"Cara merawat gigi dengan menggosok gigi rutin minimal dua kali sehari.","options":null,"explanation":"Teks: Menjaga Kesehatan Gigi. Cara merawat gigi dengan menggosok gigi rutin minimal dua kali sehari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kesehatan Gigi] Ide pokok paragraf 3 dan informasi penting.","answer":"Makanan manis dapat menyebabkan gigi berlubang jika tidak segera dibersihkan.","options":null,"explanation":"Teks: Menjaga Kesehatan Gigi. Makanan manis dapat menyebabkan gigi berlubang jika tidak segera dibersihkan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Menjaga Kesehatan Gigi] Ide pokok paragraf 4 dan informasi penting.","answer":"Kita harus rutin memeriksakan gigi ke dokter gigi setiap enam bulan sekali.","options":null,"explanation":"Teks: Menjaga Kesehatan Gigi. Kita harus rutin memeriksakan gigi ke dokter gigi setiap enam bulan sekali."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Menjaga Kesehatan Gigi] Ide pokok paragraf terakhir dan informasi penting.","answer":"Kesehatan gigi dapat dijaga dengan rajin menggosok gigi, mengurangi makanan manis, dan rutin periksa ke dokter gigi.","options":null,"explanation":"Teks: Menjaga Kesehatan Gigi. Kesehatan gigi dapat dijaga dengan rajin menggosok gigi, mengurangi makanan manis, dan rutin periksa ke dokter gigi."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Menghemat Air Bersih] Ide pokok paragraf 1 dan informasi penting.","answer":"Air merupakan sumber kehidupan yang sangat berharga bagi semua makhluk hidup.","options":null,"explanation":"Teks: Manfaat Menghemat Air Bersih. Air merupakan sumber kehidupan yang sangat berharga bagi semua makhluk hidup."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Menghemat Air Bersih] Ide pokok paragraf 2 dan informasi penting.","answer":"Ketersediaan air bersih sangat terbatas, terutama saat musim kemarau.","options":null,"explanation":"Teks: Manfaat Menghemat Air Bersih. Ketersediaan air bersih sangat terbatas, terutama saat musim kemarau."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Menghemat Air Bersih] Ide pokok paragraf 3 dan informasi penting.","answer":"Kita harus membiasakan diri menghemat penggunaan air bersih di rumah.","options":null,"explanation":"Teks: Manfaat Menghemat Air Bersih. Kita harus membiasakan diri menghemat penggunaan air bersih di rumah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Manfaat Menghemat Air Bersih] Ide pokok paragraf 4 dan informasi penting.","answer":"Menghemat air bermanfaat untuk mengurangi tagihan bulanan dan melestarikan alam.","options":null,"explanation":"Teks: Manfaat Menghemat Air Bersih. Menghemat air bermanfaat untuk mengurangi tagihan bulanan dan melestarikan alam."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Manfaat Menghemat Air Bersih] Ide pokok paragraf terakhir dan informasi penting.","answer":"Air bersih harus dihemat karena jumlahnya terbatas dan sangat penting untuk kelangsungan makhluk hidup.","options":null,"explanation":"Teks: Manfaat Menghemat Air Bersih. Air bersih harus dihemat karena jumlahnya terbatas dan sangat penting untuk kelangsungan makhluk hidup."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pameran Pakaian Adat Nusantara] Ide pokok paragraf 1 dan informasi penting.","answer":"SD Mutiara mengadakan pameran budaya memakai pakaian adat Nusantara.","options":null,"explanation":"Teks: Pameran Pakaian Adat Nusantara. SD Mutiara mengadakan pameran budaya memakai pakaian adat Nusantara."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pameran Pakaian Adat Nusantara] Ide pokok paragraf 2 dan informasi penting.","answer":"Siswa bangga mengenakan pakaian adat dari berbagai daerah yang berbeda.","options":null,"explanation":"Teks: Pameran Pakaian Adat Nusantara. Siswa bangga mengenakan pakaian adat dari berbagai daerah yang berbeda."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pameran Pakaian Adat Nusantara] Ide pokok paragraf 3 dan informasi penting.","answer":"Tujuan pameran adalah mengenalkan kekayaan budaya bangsa kepada siswa.","options":null,"explanation":"Teks: Pameran Pakaian Adat Nusantara. Tujuan pameran adalah mengenalkan kekayaan budaya bangsa kepada siswa."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pameran Pakaian Adat Nusantara] Ide pokok paragraf 4 dan informasi penting.","answer":"Acara ditutup dengan tarian tradisional yang menumbuhkan rasa cinta tanah air.","options":null,"explanation":"Teks: Pameran Pakaian Adat Nusantara. Acara ditutup dengan tarian tradisional yang menumbuhkan rasa cinta tanah air."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pameran Pakaian Adat Nusantara] Ide pokok paragraf terakhir dan informasi penting.","answer":"Pameran pakaian adat diadakan untuk mengenalkan keberagaman budaya Indonesia dan menumbuhkan rasa persatuan serta cinta tanah air.","options":null,"explanation":"Teks: Pameran Pakaian Adat Nusantara. Pameran pakaian adat diadakan untuk mengenalkan keberagaman budaya Indonesia dan menumbuhkan rasa persatuan serta cinta tanah air."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Hemat Energi Listrik di Rumah] Ide pokok paragraf 1 dan informasi penting.","answer":"Energi listrik adalah kebutuhan utama manusia untuk menyalakan berbagai peralatan.","options":null,"explanation":"Teks: Hemat Energi Listrik di Rumah. Energi listrik adalah kebutuhan utama manusia untuk menyalakan berbagai peralatan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Hemat Energi Listrik di Rumah] Ide pokok paragraf 2 dan informasi penting.","answer":"Kita tidak boleh boros karena bahan bakar pembangkit listrik semakin terbatas dan menyebabkan polusi.","options":null,"explanation":"Teks: Hemat Energi Listrik di Rumah. Kita tidak boleh boros karena bahan bakar pembangkit listrik semakin terbatas dan menyebabkan polusi."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Hemat Energi Listrik di Rumah] Ide pokok paragraf 3 dan informasi penting.","answer":"Cara menghemat listrik dengan mematikan televisi dan lampu yang tidak dipakai.","options":null,"explanation":"Teks: Hemat Energi Listrik di Rumah. Cara menghemat listrik dengan mematikan televisi dan lampu yang tidak dipakai."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Hemat Energi Listrik di Rumah] Ide pokok paragraf 4 dan informasi penting.","answer":"Keuntungan menghemat listrik adalah menghemat biaya dan menjaga bumi.","options":null,"explanation":"Teks: Hemat Energi Listrik di Rumah. Keuntungan menghemat listrik adalah menghemat biaya dan menjaga bumi."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Hemat Energi Listrik di Rumah] Ide pokok paragraf terakhir dan informasi penting.","answer":"Energi listrik sangat penting, sehingga harus digunakan dengan hemat agar bahan bakarnya tidak cepat habis dan tagihan listrik lebih murah.","options":null,"explanation":"Teks: Hemat Energi Listrik di Rumah. Energi listrik sangat penting, sehingga harus digunakan dengan hemat agar bahan bakarnya tidak cepat habis dan tagihan listrik lebih murah."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Terjadinya Gerhana Bulan] Ide pokok paragraf 1 dan informasi penting.","answer":"Gerhana bulan adalah fenomena alam menakjubkan yang terjadi saat bulan purnama.","options":null,"explanation":"Teks: Terjadinya Gerhana Bulan. Gerhana bulan adalah fenomena alam menakjubkan yang terjadi saat bulan purnama."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Terjadinya Gerhana Bulan] Ide pokok paragraf 2 dan informasi penting.","answer":"Proses gerhana bulan terjadi karena Matahari, Bumi, dan Bulan berada pada satu garis lurus.","options":null,"explanation":"Teks: Terjadinya Gerhana Bulan. Proses gerhana bulan terjadi karena Matahari, Bumi, dan Bulan berada pada satu garis lurus."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Terjadinya Gerhana Bulan] Ide pokok paragraf 3 dan informasi penting.","answer":"Jenis-jenis gerhana bulan meliputi gerhana bulan total dan sebagian.","options":null,"explanation":"Teks: Terjadinya Gerhana Bulan. Jenis-jenis gerhana bulan meliputi gerhana bulan total dan sebagian."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty":5,"question":"[Terjadinya Gerhana Bulan] Ide pokok paragraf 4 dan informasi penting.","answer":"Gerhana bulan sangat aman disaksikan secara langsung dengan mata telanjang.","options":null,"explanation":"Teks: Terjadinya Gerhana Bulan. Gerhana bulan sangat aman disaksikan secara langsung dengan mata telanjang."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty":5,"question":"[Terjadinya Gerhana Bulan] Ide pokok paragraf terakhir dan informasi penting.","answer":"Gerhana bulan terjadi karena cahaya matahari ke bulan terhalang oleh bumi, dan fenomena ini aman dilihat secara langsung.","options":null,"explanation":"Teks: Terjadinya Gerhana Bulan. Gerhana bulan terjadi karena cahaya matahari ke bulan terhalang oleh bumi, dan fenomena ini aman dilihat secara langsung."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Proses Terjadinya Hujan (Siklus Air)] Ide pokok paragraf 1 dan informasi penting.","answer":"Hujan berasal dari proses perputaran air di bumi yang disebut siklus air.","options":null,"explanation":"Teks: Proses Terjadinya Hujan (Siklus Air). Hujan berasal dari proses perputaran air di bumi yang disebut siklus air."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Proses Terjadinya Hujan (Siklus Air)] Ide pokok paragraf 2 dan informasi penting.","answer":"Tahap penguapan (evaporasi) terjadi saat panas matahari mengubah air laut menjadi uap.","options":null,"explanation":"Teks: Proses Terjadinya Hujan (Siklus Air). Tahap penguapan (evaporasi) terjadi saat panas matahari mengubah air laut menjadi uap."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Proses Terjadinya Hujan (Siklus Air)] Ide pokok paragraf 3 dan informasi penting.","answer":"Tahap pembentukan awan (kondensasi) terjadi ketika uap air berubah menjadi titik-titik air di langit.","options":null,"explanation":"Teks: Proses Terjadinya Hujan (Siklus Air). Tahap pembentukan awan (kondensasi) terjadi ketika uap air berubah menjadi titik-titik air di langit."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Proses Terjadinya Hujan (Siklus Air)] Ide pokok paragraf 4 dan informasi penting.","answer":"Titik air di awan yang terlalu berat akan jatuh ke bumi sebagai hujan.","options":null,"explanation":"Teks: Proses Terjadinya Hujan (Siklus Air). Titik air di awan yang terlalu berat akan jatuh ke bumi sebagai hujan."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Proses Terjadinya Hujan (Siklus Air)] Ide pokok paragraf terakhir dan informasi penting.","answer":"Hujan terjadi melalui siklus air, yaitu proses penguapan air di bumi yang membentuk awan dan akhirnya jatuh kembali sebagai hujan.","options":null,"explanation":"Teks: Proses Terjadinya Hujan (Siklus Air). Hujan terjadi melalui siklus air, yaitu proses penguapan air di bumi yang membentuk awan dan akhirnya jatuh kembali sebagai hujan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Energi Alternatif] Ide pokok paragraf 1 dan informasi penting.","answer":"Manusia mengembangkan energi alternatif karena bahan bakar fosil terbatas dan bisa habis.","options":null,"explanation":"Teks: Pentingnya Energi Alternatif. Manusia mengembangkan energi alternatif karena bahan bakar fosil terbatas dan bisa habis."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Energi Alternatif] Ide pokok paragraf 2 dan informasi penting.","answer":"Tenaga surya dari matahari bisa diubah menjadi listrik menggunakan panel surya.","options":null,"explanation":"Teks: Pentingnya Energi Alternatif. Tenaga surya dari matahari bisa diubah menjadi listrik menggunakan panel surya."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Energi Alternatif] Ide pokok paragraf 3 dan informasi penting.","answer":"Tenaga angin dimanfaatkan untuk menghasilkan listrik melalui kincir angin.","options":null,"explanation":"Teks: Pentingnya Energi Alternatif. Tenaga angin dimanfaatkan untuk menghasilkan listrik melalui kincir angin."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Energi Alternatif] Ide pokok paragraf 4 dan informasi penting.","answer":"Keuntungan energi alternatif adalah lebih bersih dan ramah lingkungan.","options":null,"explanation":"Teks: Pentingnya Energi Alternatif. Keuntungan energi alternatif adalah lebih bersih dan ramah lingkungan."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pentingnya Energi Alternatif] Ide pokok paragraf terakhir dan informasi penting.","answer":"Energi alternatif seperti tenaga surya dan angin sangat penting dikembangkan untuk menggantikan bahan bakar fosil dan menjaga kebersihan lingkungan.","options":null,"explanation":"Teks: Pentingnya Energi Alternatif. Energi alternatif seperti tenaga surya dan angin sangat penting dikembangkan untuk menggantikan bahan bakar fosil dan menjaga kebersihan lingkungan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Candi Borobudur sebagai Warisan Dunia] Ide pokok paragraf 1 dan informasi penting.","answer":"Candi Borobudur di Jawa Tengah adalah candi Buddha terbesar di dunia.","options":null,"explanation":"Teks: Candi Borobudur sebagai Warisan Dunia. Candi Borobudur di Jawa Tengah adalah candi Buddha terbesar di dunia."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Candi Borobudur sebagai Warisan Dunia] Ide pokok paragraf 2 dan informasi penting.","answer":"Candi Borobudur dibangun oleh Wangsa Syailendra menggunakan batu tanpa semen.","options":null,"explanation":"Teks: Candi Borobudur sebagai Warisan Dunia. Candi Borobudur dibangun oleh Wangsa Syailendra menggunakan batu tanpa semen."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Candi Borobudur sebagai Warisan Dunia] Ide pokok paragraf 3 dan informasi penting.","answer":"Candi Borobudur memiliki arsitektur menakjubkan berupa relief dan stupa.","options":null,"explanation":"Teks: Candi Borobudur sebagai Warisan Dunia. Candi Borobudur memiliki arsitektur menakjubkan berupa relief dan stupa."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Candi Borobudur sebagai Warisan Dunia] Ide pokok paragraf 4 dan informasi penting.","answer":"Candi Borobudur diakui sebagai Situs Warisan Dunia UNESCO sehingga harus dijaga.","options":null,"explanation":"Teks: Candi Borobudur sebagai Warisan Dunia. Candi Borobudur diakui sebagai Situs Warisan Dunia UNESCO sehingga harus dijaga."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Candi Borobudur sebagai Warisan Dunia] Ide pokok paragraf terakhir dan informasi penting.","answer":"Candi Borobudur adalah candi Buddha terbesar dan megah di dunia yang diakui UNESCO, sehingga kelestariannya harus dijaga bersama.","options":null,"explanation":"Teks: Candi Borobudur sebagai Warisan Dunia. Candi Borobudur adalah candi Buddha terbesar dan megah di dunia yang diakui UNESCO, sehingga kelestariannya harus dijaga bersama."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Sistem Pencernaan Manusia] Ide pokok paragraf 1 dan informasi penting.","answer":"Sistem pencernaan adalah proses penghancuran makanan di dalam tubuh manusia.","options":null,"explanation":"Teks: Sistem Pencernaan Manusia. Sistem pencernaan adalah proses penghancuran makanan di dalam tubuh manusia."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Sistem Pencernaan Manusia] Ide pokok paragraf 2 dan informasi penting.","answer":"Pencernaan makanan dimulai dari mulut dengan bantuan gigi dan air liur.","options":null,"explanation":"Teks: Sistem Pencernaan Manusia. Pencernaan makanan dimulai dari mulut dengan bantuan gigi dan air liur."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Sistem Pencernaan Manusia] Ide pokok paragraf 3 dan informasi penting.","answer":"Di lambung, makanan diremas dan dicerna dengan bantuan asam lambung.","options":null,"explanation":"Teks: Sistem Pencernaan Manusia. Di lambung, makanan diremas dan dicerna dengan bantuan asam lambung."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Sistem Pencernaan Manusia] Ide pokok paragraf 4 dan informasi penting.","answer":"Usus halus menyerap sari makanan, sedangkan usus besar membuang sisa makanan.","options":null,"explanation":"Teks: Sistem Pencernaan Manusia. Usus halus menyerap sari makanan, sedangkan usus besar membuang sisa makanan."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Sistem Pencernaan Manusia] Ide pokok paragraf terakhir dan informasi penting.","answer":"Sistem pencernaan mengubah makanan dari mulut, lambung, hingga usus agar nutrisinya bisa diserap tubuh dan sisanya dibuang.","options":null,"explanation":"Teks: Sistem Pencernaan Manusia. Sistem pencernaan mengubah makanan dari mulut, lambung, hingga usus agar nutrisinya bisa diserap tubuh dan sisanya dibuang."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Keunikan Burung Hantu] Ide pokok paragraf 1 dan informasi penting.","answer":"Burung hantu adalah hewan nokturnal yang aktif mencari mangsa di malam hari.","options":null,"explanation":"Teks: Keunikan Burung Hantu. Burung hantu adalah hewan nokturnal yang aktif mencari mangsa di malam hari."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Keunikan Burung Hantu] Ide pokok paragraf 2 dan informasi penting.","answer":"Burung hantu memiliki penglihatan dan pendengaran yang sangat tajam.","options":null,"explanation":"Teks: Keunikan Burung Hantu. Burung hantu memiliki penglihatan dan pendengaran yang sangat tajam."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Keunikan Burung Hantu] Ide pokok paragraf 3 dan informasi penting.","answer":"Leher burung hantu sangat lentur dan bisa berputar hingga hampir satu lingkaran penuh.","options":null,"explanation":"Teks: Keunikan Burung Hantu. Leher burung hantu sangat lentur dan bisa berputar hingga hampir satu lingkaran penuh."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Keunikan Burung Hantu] Ide pokok paragraf 4 dan informasi penting.","answer":"Bulu sayap yang halus membuat burung hantu bisa terbang terbang tanpa suara.","options":null,"explanation":"Teks: Keunikan Burung Hantu. Bulu sayap yang halus membuat burung hantu bisa terbang terbang tanpa suara."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Keunikan Burung Hantu] Ide pokok paragraf terakhir dan informasi penting.","answer":"Burung hantu adalah pemburu malam yang hebat karena memiliki penglihatan tajam, leher lentur, dan kemampuan terbang tanpa suara.","options":null,"explanation":"Teks: Keunikan Burung Hantu. Burung hantu adalah pemburu malam yang hebat karena memiliki penglihatan tajam, leher lentur, dan kemampuan terbang tanpa suara."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Vaksinasi bagi Kesehatan] Ide pokok paragraf 1 dan informasi penting.","answer":"Vaksinasi adalah cara paling ampuh untuk mencegah penyakit menular.","options":null,"explanation":"Teks: Pentingnya Vaksinasi bagi Kesehatan. Vaksinasi adalah cara paling ampuh untuk mencegah penyakit menular."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Vaksinasi bagi Kesehatan] Ide pokok paragraf 2 dan informasi penting.","answer":"Vaksin merangsang tubuh untuk memproduksi zat pertahanan bernama antibodi.","options":null,"explanation":"Teks: Pentingnya Vaksinasi bagi Kesehatan. Vaksin merangsang tubuh untuk memproduksi zat pertahanan bernama antibodi."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Vaksinasi bagi Kesehatan] Ide pokok paragraf 3 dan informasi penting.","answer":"Antibodi dari vaksin membuat tubuh siap melawan virus jahat di masa depan.","options":null,"explanation":"Teks: Pentingnya Vaksinasi bagi Kesehatan. Antibodi dari vaksin membuat tubuh siap melawan virus jahat di masa depan."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pentingnya Vaksinasi bagi Kesehatan] Ide pokok paragraf 4 dan informasi penting.","answer":"Vaksinasi massal menciptakan kekebalan kelompok yang melindungi seluruh masyarakat.","options":null,"explanation":"Teks: Pentingnya Vaksinasi bagi Kesehatan. Vaksinasi massal menciptakan kekebalan kelompok yang melindungi seluruh masyarakat."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pentingnya Vaksinasi bagi Kesehatan] Ide pokok paragraf terakhir dan informasi penting.","answer":"Vaksinasi sangat penting karena membentuk antibodi pelindung di dalam tubuh yang mencegah kita dan orang lain dari penyakit menular.","options":null,"explanation":"Teks: Pentingnya Vaksinasi bagi Kesehatan. Vaksinasi sangat penting karena membentuk antibodi pelindung di dalam tubuh yang mencegah kita dan orang lain dari penyakit menular."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pemanasan Global dan Akibatnya] Ide pokok paragraf 1 dan informasi penting.","answer":"Pemanasan global adalah meningkatnya suhu rata-rata di bumi secara cepat akibat aktivitas manusia.","options":null,"explanation":"Teks: Pemanasan Global dan Akibatnya. Pemanasan global adalah meningkatnya suhu rata-rata di bumi secara cepat akibat aktivitas manusia."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pemanasan Global dan Akibatnya] Ide pokok paragraf 2 dan informasi penting.","answer":"Gas rumah kaca dari polusi dan pembakaran hutan adalah penyebab utama pemanasan global.","options":null,"explanation":"Teks: Pemanasan Global dan Akibatnya. Gas rumah kaca dari polusi dan pembakaran hutan adalah penyebab utama pemanasan global."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pemanasan Global dan Akibatnya] Ide pokok paragraf 3 dan informasi penting.","answer":"Dampak pemanasan global meliputi mencairnya es kutub, naiknya air laut, dan cuaca ekstrem.","options":null,"explanation":"Teks: Pemanasan Global dan Akibatnya. Dampak pemanasan global meliputi mencairnya es kutub, naiknya air laut, dan cuaca ekstrem."},
  {"category":"membaca","subcategory":"ide_pokok","type":"isian","difficulty": 5,"question":"[Pemanasan Global dan Akibatnya] Ide pokok paragraf 4 dan informasi penting.","answer":"Kita bisa mencegah pemanasan global dengan menanam pohon dan mengurangi polusi.","options":null,"explanation":"Teks: Pemanasan Global dan Akibatnya. Kita bisa mencegah pemanasan global dengan menanam pohon dan mengurangi polusi."},
  {"category":"membaca","subcategory":"informasi_penting","type":"isian","difficulty": 5,"question":"[Pemanasan Global dan Akibatnya] Ide pokok paragraf terakhir dan informasi penting.","answer":"Pemanasan global yang disebabkan oleh gas rumah kaca sangat berbahaya bagi bumi, sehingga manusia harus segera melakukan tindakan pelestarian lingkungan.","options":null,"explanation":"Teks: Pemanasan Global dan Akibatnya. Pemanasan global yang disebabkan oleh gas rumah kaca sangat berbahaya bagi bumi, sehingga manusia harus segera melakukan tindakan pelestarian lingkungan."},
];
